name: Build

on:
  push:
    paths:
      - 'airsaned/**'
      - '.github/**'

jobs:
  build:
    strategy:
      matrix:
        wrtrel: ['23.05.0']
        sdk: ['ramips-mt76x8', 'bcm27xx-bcm2708']
        include:
          - sdk: ramips-mt76x8
            target: mipsel_24kc
          - sdk: bcm27xx-bcm2708
            target: arm_arm1176jzf-s_vfp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Makefile
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            airsaned/Makefile
          sparse-checkout-cone-mode: false

      - name: Get version
        run: |
          export MAKEFILE="/home/runner/work/AirSane-openwrt/AirSane-openwrt/airsaned/Makefile"
          export PKG_SOURCE_DATE=`sed -n "s/^PKG_SOURCE_DATE:=\(.*\)$/\1/p" $MAKEFILE`
          export PKG_SOURCE_VERSION=`sed -n "s/^PKG_SOURCE_VERSION:=\(.*\)$/\1/p" $MAKEFILE`
          export PKG_RELEASE=`sed -n "s/^PKG_RELEASE:=\(.*\)$/\1/p" $MAKEFILE`
          export PKG_VERSION="$PKG_SOURCE_DATE-$PKG_SOURCE_VERSION"
          echo "PKG_VERSION=$PKG_VERSION" >> $GITHUB_ENV
          echo "PKG_FULL_VERSION=$PKG_VERSION-$PKG_RELEASE" >> $GITHUB_ENV

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.sdk }}-${{ matrix.wrtrel }}
          EXTRA_FEEDS: src-git|airsaned|https://github.com/cmangla/AirSane-openwrt.git^${{ github.sha }}
          PACKAGES: airsaned
          V: s


      - name: Upload app binary
        uses: actions/upload-artifact@v3
        with:
          name: airsaned_${{ env.PKG_FULL_VERSION }}_${{ matrix.target }}_openwrt-${{ matrix.wrtrel }}.ipk
          path: /artifacts/packages/${{ matrix.target }}/airsaned/airsaned_${{ env.PKG_FULL_VERSION }}_${{ matrix.target }}.ipk
