name: Build Airsaned packages

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        wrtrel: ['22.03.2', '23.05.0', '23.05.2']
        sdk: ['ramips-mt76x8', 'bcm27xx-bcm2708']

    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Build Airsaned package for OpenWRT
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.sdk }}-${{ matrix.wrtrel }}
          EXTRA_FEEDS: src-git|airsaned|${{ github.server_url }}/${{ github.repository }}.git^${{ github.sha }}
          PACKAGES: airsaned

      - name: Obtain full package version
        run: bash ./.github/work.sh pkg-ver airsaned/Makefile | tee $GITHUB_ENV
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: airsaned_${{ env.PKG_FULL_VERSION }}_openwrt-${{ matrix.wrtrel }}_${{ matrix.sdk }}.ipk
          path: bin/packages/**/airsaned_*.ipk

