name: build

on:
  push:
    paths:
      - 'airsaned/**'
      - '.github/**'

  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        wrtrel: ['22.03.2']
        sdk: ['ramips-mt76x8', 'bcm27xx-bcm2708']
        include:
          - sdk: ramips-mt76x8
            target: mipsel_24kc
          - sdk: bcm27xx-bcm2708
            target: arm_arm1176jzf-s_vfp

    runs-on: ubuntu-latest

    container: 
      image: openwrt/sdk:${{ matrix.sdk }}-${{ matrix.wrtrel }}
      options: --user root

    defaults:
      run:
        working-directory: /home/build/openwrt

    steps:

      - name: Add feeds
        run: echo "src-git airsaned https://github.com/cmangla/AirSane-openwrt.git^${GITHUB_SHA}" >> feeds.conf.default

      - name: Update feeds
        run: ./scripts/feeds update base packages airsaned

      - name: Make defconfig
        run: make defconfig

      - name: Install feeds
        run: ./scripts/feeds install airsaned

      - name: Compile
        run: make package/airsaned/compile -j$(nproc)

      - name: Get version
        run: |
          export MAKEFILE="./feeds/airsaned/airsaned/Makefile"
          export PKG_SOURCE_DATE=`sed -n "s/^PKG_SOURCE_DATE:=\(.*\)$/\1/p" $MAKEFILE`
          export PKG_SOURCE_VERSION=`sed -n "s/^PKG_SOURCE_VERSION:=\(.*\)$/\1/p" $MAKEFILE`
          export PKG_RELEASE=`sed -n "s/^PKG_RELEASE:=\(.*\)$/\1/p" $MAKEFILE`
          export PKG_VERSION="$PKG_SOURCE_DATE-$PKG_SOURCE_VERSION"
          echo "PKG_VERSION=$PKG_VERSION" >> $GITHUB_ENV
          echo "PKG_FULL_VERSION=$PKG_VERSION-$PKG_RELEASE" >> $GITHUB_ENV

      - name: Upload app binary
        uses: actions/upload-artifact@v3
        with:
          name: airsaned_${{ env.PKG_FULL_VERSION }}_openwrt-${{ matrix.wrtrel }}_${{ matrix.target }}.ipk
          path: /home/build/openwrt/bin/packages/${{ matrix.target }}/airsaned/airsaned_${{ env.PKG_FULL_VERSION }}_${{ matrix.target }}.ipk

  build_post_r23:
    strategy:
      matrix:
        wrtrel: ['23.05.0', '23.05.2']
        sdk: ['ramips-mt76x8', 'bcm27xx-bcm2708']
        include:
          - sdk: ramips-mt76x8
            target: mipsel_24kc
          - sdk: bcm27xx-bcm2708
            target: arm_arm1176jzf-s_vfp

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.sdk }}-${{ matrix.wrtrel }}
          EXTRA_FEEDS: src-git|airsaned|https://github.com/cmangla/AirSane-openwrt.git^${{ github.sha }}
          PACKAGES: airsaned

      - name: Get version
        run: |
          export MAKEFILE="airsaned/Makefile"
          export PKG_SOURCE_DATE=`sed -n "s/^PKG_SOURCE_DATE:=\(.*\)$/\1/p" $MAKEFILE`
          export PKG_SOURCE_VERSION=`sed -n "s/^PKG_SOURCE_VERSION:=\(.*\)$/\1/p" $MAKEFILE`
          export PKG_RELEASE=`sed -n "s/^PKG_RELEASE:=\(.*\)$/\1/p" $MAKEFILE`
          export PKG_VERSION="$PKG_SOURCE_DATE-$PKG_SOURCE_VERSION"
          echo "PKG_FULL_VERSION=$PKG_VERSION-$PKG_RELEASE" >> $GITHUB_ENV

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: airsaned_${{ env.PKG_FULL_VERSION }}_openwrt-${{ matrix.wrtrel }}_${{ matrix.target }}.ipk
          path: bin/packages/**/airsaned_*.ipk

