name: build

on:
  push:
    paths:
      - 'airsaned/**'
      - '.github/**'

  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        wrtrel: ['22.03.2']
        sdk: ['ramips-mt76x8', 'bcm27xx-bcm2708']

    runs-on: ubuntu-latest

    container: 
      image: openwrt/sdk:${{ matrix.sdk }}-${{ matrix.wrtrel }}
      options: --user root

    defaults:
      run:
        working-directory: /home/build/openwrt

    steps:

      - name: Add AirSane feed
        run: echo "src-git airsaned https://github.com/cmangla/AirSane-openwrt.git^${GITHUB_SHA}" >> feeds.conf.default

      - name: Update feeds
        run: ./scripts/feeds update base packages airsaned

      - run: make defconfig

      - run: ./scripts/feeds install airsaned

      - run: make package/airsaned/compile -j"$(nproc)"

      - name: Get version
        run: |
          export MAKEFILE="./feeds/airsaned/airsaned/Makefile"
          export PKG_SOURCE_DATE=`sed -n "s/^PKG_SOURCE_DATE:=\(.*\)$/\1/p" $MAKEFILE`
          export PKG_SOURCE_VERSION=`sed -n "s/^PKG_SOURCE_VERSION:=\(.*\)$/\1/p" $MAKEFILE`
          export PKG_RELEASE=`sed -n "s/^PKG_RELEASE:=\(.*\)$/\1/p" $MAKEFILE`
          export PKG_VERSION="$PKG_SOURCE_DATE-$PKG_SOURCE_VERSION"
          echo "PKG_FULL_VERSION=$PKG_VERSION-$PKG_RELEASE" >> $GITHUB_ENV

      - run: find . -name 'airsaned_*.ipk' -exec realpath '{}' \;

      - uses: actions/upload-artifact@v3
        with:
          name: airsaned_${{ env.PKG_FULL_VERSION }}_openwrt-${{ matrix.wrtrel }}_${{ matrix.sdk }}.ipk
          path: /home/build/openwrt/bin/packages/**/airsaned_*.ipk

  build_post_r23:
    strategy:
      matrix:
        wrtrel: ['23.05.0', '23.05.2']
        sdk: ['ramips-mt76x8', 'bcm27xx-bcm2708']

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.sdk }}-${{ matrix.wrtrel }}
          EXTRA_FEEDS: src-git|airsaned|https://github.com/cmangla/AirSane-openwrt.git^${{ github.sha }}
          PACKAGES: airsaned

      - name: Get version
        run: |
          export MAKEFILE="airsaned/Makefile"
          export PKG_SOURCE_DATE=`sed -n "s/^PKG_SOURCE_DATE:=\(.*\)$/\1/p" $MAKEFILE`
          export PKG_SOURCE_VERSION=`sed -n "s/^PKG_SOURCE_VERSION:=\(.*\)$/\1/p" $MAKEFILE`
          export PKG_RELEASE=`sed -n "s/^PKG_RELEASE:=\(.*\)$/\1/p" $MAKEFILE`
          export PKG_VERSION="$PKG_SOURCE_DATE-$PKG_SOURCE_VERSION"
          echo "PKG_FULL_VERSION=$PKG_VERSION-$PKG_RELEASE" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v3
        with:
          name: airsaned_${{ env.PKG_FULL_VERSION }}_openwrt-${{ matrix.wrtrel }}_${{ matrix.sdk }}.ipk
          path: bin/packages/**/airsaned_*.ipk

