name: build_post_r23

on:
  push:
    paths:
      - 'airsaned/**'
      - '.github/**'

jobs:
  build_post_r23:
    strategy:
      matrix:
        wrtrel: ['23.05.0', '23.05.2']
        sdk: ['ramips-mt76x8', 'bcm27xx-bcm2708']
        include:
          - sdk: ramips-mt76x8
            target: mipsel_24kc
          - sdk: bcm27xx-bcm2708
            target: arm_arm1176jzf-s_vfp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.sdk }}-${{ matrix.wrtrel }}
          EXTRA_FEEDS: src-git|airsaned|https://github.com/cmangla/AirSane-openwrt.git^${{ github.sha }}
          PACKAGES: airsaned

      - name: Get version
        run: |
          export MAKEFILE="airsaned/Makefile"
          export PKG_SOURCE_DATE=`sed -n "s/^PKG_SOURCE_DATE:=\(.*\)$/\1/p" $MAKEFILE`
          export PKG_SOURCE_VERSION=`sed -n "s/^PKG_SOURCE_VERSION:=\(.*\)$/\1/p" $MAKEFILE`
          export PKG_RELEASE=`sed -n "s/^PKG_RELEASE:=\(.*\)$/\1/p" $MAKEFILE`
          export PKG_VERSION="$PKG_SOURCE_DATE-$PKG_SOURCE_VERSION"
          echo "PKG_FULL_VERSION=$PKG_VERSION-$PKG_RELEASE" >> $GITHUB_ENV

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: airsaned_${{ env.PKG_FULL_VERSION }}_openwrt-${{ matrix.wrtrel }}_${{ matrix.target }}.ipk
          path: bin/packages/**/airsaned_*.ipk
