name: release

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build_all:
    uses: ./.github/workflows/build.yml

  release:
    name: Obtain release artifacts
    needs: [build_all]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v3
      - run: |
          mkdir release-packages
          find . -type d -name '*.ipk' | while IFS= read -r pk; do
            pkf=$(find "$pk" -name '*.ipk' -type f | tail -n1)
            cp -v "$pkf" "release-packages/${pk}"
          done
      - uses: softprops/action-gh-release@v1
        with:
          files: release-packages/*.ipk

