name: release

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build_all:
    uses: ./.github/workflows/build.yml

  release:
    name: Obtain release artifacts
    needs: [build_all]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v3
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            *.ipk
            */*.ipk
            */*/*.ipk

