name: Make release when tag is created

on:
  push:
    tags:
      - v*
  workflow_call:
  workflow_dispatch:

jobs:
  build_all:
    uses: ./.github/workflows/build.yml

  release:
    name: Obtain release artifacts
    needs: [build_all]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4.1.7
      - run: |
          mkdir release-packages
          find . -type d -name '*.ipk.d' | while IFS= read -r pkd; do
            cp -v $(find "$pkd" -name '*.ipk' -type f) release-packages/
          done
      - name: Create new release from tag
        uses: softprops/action-gh-release@v1
        with:
          files: release-packages/*.ipk
